-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-04-19 21:48:58 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE cliente CASCADE CONSTRAINTS;

DROP TABLE compra CASCADE CONSTRAINTS;

DROP TABLE correo CASCADE CONSTRAINTS;

DROP TABLE cuenta_bancaria CASCADE CONSTRAINTS;

DROP TABLE debito CASCADE CONSTRAINTS;

DROP TABLE deposito CASCADE CONSTRAINTS;

DROP TABLE historial CASCADE CONSTRAINTS;

DROP TABLE producto_servicio CASCADE CONSTRAINTS;

DROP TABLE telefono CASCADE CONSTRAINTS;

DROP TABLE tip_trans CASCADE CONSTRAINTS;

DROP TABLE tipo_cliente CASCADE CONSTRAINTS;

DROP TABLE tipo_cuenta CASCADE CONSTRAINTS;

DROP TABLE transaccion CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cliente (
    id_cliente           INTEGER NOT NULL,
    nombre               VARCHAR2(200) NOT NULL,
    apellidos            VARCHAR2(200) NOT NULL,
    usuario              VARCHAR2(200) NOT NULL,
    clave                VARCHAR2(200) NOT NULL,
    tipo_cliente_id_tipo INTEGER NOT NULL,
    fecha_c              DATE NOT NULL
);

ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY ( id_cliente );

CREATE TABLE compra (
    id_compra                   INTEGER NOT NULL,
    fecha                       DATE NOT NULL,
    importe_compra              NUMBER(12, 2) NOT NULL,
    otros_detalles              VARCHAR2(200),
    cliente_id_cliente          INTEGER NOT NULL,
    producto_servicio_id_produc INTEGER NOT NULL
);

ALTER TABLE compra ADD CONSTRAINT compra_pk PRIMARY KEY ( id_compra );

CREATE TABLE correo (
    correo             VARCHAR2(200) NOT NULL,
    cliente_id_cliente INTEGER NOT NULL
);

ALTER TABLE correo ADD CONSTRAINT correo_pk PRIMARY KEY ( correo,
                                                          cliente_id_cliente );

CREATE TABLE cuenta_bancaria (
    id_cuenta                  INTEGER NOT NULL,
    monto_apertura             NUMBER(12, 2) NOT NULL,
    saldo_cuenta               NUMBER(12, 2) NOT NULL,
    descripcion                VARCHAR2(200) NOT NULL,
    fecha_apertura             TIMESTAMP NOT NULL,
    otros_detalles             VARCHAR2(200),
    tipo_cuenta_id_tipo_cuenta INTEGER NOT NULL,
    cliente_id_cliente         INTEGER NOT NULL
);

ALTER TABLE cuenta_bancaria ADD CONSTRAINT cuenta_bancaria_pk PRIMARY KEY ( id_cuenta );

CREATE TABLE debito (
    id_deb             INTEGER NOT NULL,
    fecha              DATE NOT NULL,
    monto              NUMBER(12, 2) NOT NULL,
    otros_detalles     VARCHAR2(200),
    cliente_id_cliente INTEGER NOT NULL
);

ALTER TABLE debito ADD CONSTRAINT debito_pk PRIMARY KEY ( id_deb );

CREATE TABLE deposito (
    id_dep             INTEGER NOT NULL,
    fecha              DATE NOT NULL,
    monto              NUMBER(12, 2) NOT NULL,
    otros_detalles     VARCHAR2(200),
    cliente_id_cliente INTEGER NOT NULL
);

ALTER TABLE deposito ADD CONSTRAINT deposito_pk PRIMARY KEY ( id_dep );

CREATE TABLE historial (
    id_histo INTEGER NOT NULL,
    fecha    TIMESTAMP NOT NULL,
    descrip  VARCHAR2(200) NOT NULL,
    tipo     VARCHAR2(200) NOT NULL
);

ALTER TABLE historial ADD CONSTRAINT historial_pk PRIMARY KEY ( id_histo );

CREATE TABLE producto_servicio (
    id_produc  INTEGER NOT NULL,
    tipo       INTEGER NOT NULL,
    costo      NUMBER(12, 2) NOT NULL,
    des_produc VARCHAR2(200) NOT NULL
);

ALTER TABLE producto_servicio ADD CONSTRAINT producto_servicio_pk PRIMARY KEY ( id_produc );

CREATE TABLE telefono (
    telefono           VARCHAR2(200) NOT NULL,
    cliente_id_cliente INTEGER NOT NULL
);

ALTER TABLE telefono ADD CONSTRAINT telefono_pk PRIMARY KEY ( telefono,
                                                              cliente_id_cliente );

CREATE TABLE tip_trans (
    id_tipo_trans INTEGER NOT NULL,
    nombre        VARCHAR2(200) NOT NULL,
    descripcion   VARCHAR2(200) NOT NULL
);

ALTER TABLE tip_trans ADD CONSTRAINT tip_trans_pk PRIMARY KEY ( id_tipo_trans );

CREATE TABLE tipo_cliente (
    id_tipo     INTEGER NOT NULL,
    nombre      VARCHAR2(200) NOT NULL,
    descripcion VARCHAR2(200) NOT NULL
);

ALTER TABLE tipo_cliente ADD CONSTRAINT tipo_cliente_pk PRIMARY KEY ( id_tipo );

CREATE TABLE tipo_cuenta (
    id_tipo_cuenta INTEGER NOT NULL,
    nombre         VARCHAR2(200) NOT NULL,
    descripcion    VARCHAR2(200) NOT NULL
);

ALTER TABLE tipo_cuenta ADD CONSTRAINT tipo_cuenta_pk PRIMARY KEY ( id_tipo_cuenta );

CREATE TABLE transaccion (
    id_trans                  INTEGER NOT NULL,
    fecha                     DATE NOT NULL,
    otros_detalles            VARCHAR2(200),
    debito_id_deb             INTEGER NOT NULL,
    compra_id_compra          INTEGER NOT NULL,
    deposito_id_dep           INTEGER NOT NULL,
    tip_trans_id_tipo_trans   INTEGER NOT NULL,
    cuenta_bancaria_id_cuenta INTEGER NOT NULL
);

ALTER TABLE transaccion ADD CONSTRAINT transaccion_pk PRIMARY KEY ( id_trans );

ALTER TABLE cliente
    ADD CONSTRAINT cliente_tipo_cliente_fk FOREIGN KEY ( tipo_cliente_id_tipo )
        REFERENCES tipo_cliente ( id_tipo );

ALTER TABLE compra
    ADD CONSTRAINT compra_cliente_fk FOREIGN KEY ( cliente_id_cliente )
        REFERENCES cliente ( id_cliente );

ALTER TABLE compra
    ADD CONSTRAINT compra_producto_servicio_fk FOREIGN KEY ( producto_servicio_id_produc )
        REFERENCES producto_servicio ( id_produc );

ALTER TABLE correo
    ADD CONSTRAINT correo_cliente_fk FOREIGN KEY ( cliente_id_cliente )
        REFERENCES cliente ( id_cliente );

ALTER TABLE cuenta_bancaria
    ADD CONSTRAINT cuenta_bancaria_cliente_fk FOREIGN KEY ( cliente_id_cliente )
        REFERENCES cliente ( id_cliente );

ALTER TABLE cuenta_bancaria
    ADD CONSTRAINT cuenta_bancaria_tipo_cuenta_fk FOREIGN KEY ( tipo_cuenta_id_tipo_cuenta )
        REFERENCES tipo_cuenta ( id_tipo_cuenta );

ALTER TABLE debito
    ADD CONSTRAINT debito_cliente_fk FOREIGN KEY ( cliente_id_cliente )
        REFERENCES cliente ( id_cliente );

ALTER TABLE deposito
    ADD CONSTRAINT deposito_cliente_fk FOREIGN KEY ( cliente_id_cliente )
        REFERENCES cliente ( id_cliente );

ALTER TABLE telefono
    ADD CONSTRAINT telefono_cliente_fk FOREIGN KEY ( cliente_id_cliente )
        REFERENCES cliente ( id_cliente );

ALTER TABLE transaccion
    ADD CONSTRAINT transaccion_compra_fk FOREIGN KEY ( compra_id_compra )
        REFERENCES compra ( id_compra );

ALTER TABLE transaccion
    ADD CONSTRAINT transaccion_cuenta_bancaria_fk FOREIGN KEY ( cuenta_bancaria_id_cuenta )
        REFERENCES cuenta_bancaria ( id_cuenta );

ALTER TABLE transaccion
    ADD CONSTRAINT transaccion_debito_fk FOREIGN KEY ( debito_id_deb )
        REFERENCES debito ( id_deb );

ALTER TABLE transaccion
    ADD CONSTRAINT transaccion_deposito_fk FOREIGN KEY ( deposito_id_dep )
        REFERENCES deposito ( id_dep );

ALTER TABLE transaccion
    ADD CONSTRAINT transaccion_tip_trans_fk FOREIGN KEY ( tip_trans_id_tipo_trans )
        REFERENCES tip_trans ( id_tipo_trans );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
