-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-03-14 22:27:45 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE categoria CASCADE CONSTRAINTS;

DROP TABLE cliente CASCADE CONSTRAINTS;

DROP TABLE detalle CASCADE CONSTRAINTS;

DROP TABLE orden_de_venta CASCADE CONSTRAINTS;

DROP TABLE pais CASCADE CONSTRAINTS;

DROP TABLE producto CASCADE CONSTRAINTS;

DROP TABLE vendedor CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE categoria (
    id_categoria     INTEGER NOT NULL,
    nombre_categoria VARCHAR2(50) NOT NULL
);

ALTER TABLE categoria ADD CONSTRAINT categoria_pk PRIMARY KEY ( id_categoria );

CREATE TABLE cliente (
    id_cliente       INTEGER NOT NULL,
    nombre_cliente   VARCHAR2(50) NOT NULL,
    apellido_cliente VARCHAR2(50) NOT NULL,
    direccion        VARCHAR2(50) NOT NULL,
    telefono         VARCHAR2(50) NOT NULL,
    targeta_credito  VARCHAR2(50) NOT NULL,
    edad             INTEGER NOT NULL,
    genero           VARCHAR2(50),
    salario          FLOAT,
    pais_id_pais     INTEGER NOT NULL
);

ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY ( id_cliente );

CREATE TABLE detalle (
    id_detalle              INTEGER NOT NULL,
    cantidad                INTEGER NOT NULL,
    linea_orden             INTEGER NOT NULL,
    producto_id_producto    INTEGER NOT NULL,
    orden_de_venta_id_orden INTEGER NOT NULL,
    vendedor_id_vendedor    INTEGER NOT NULL
);

ALTER TABLE detalle ADD CONSTRAINT detalle_pk PRIMARY KEY ( id_detalle );

CREATE TABLE orden_de_venta (
    id_orden           INTEGER NOT NULL,
    fecha_orden        DATE NOT NULL,
    cliente_id_cliente INTEGER NOT NULL
);

ALTER TABLE orden_de_venta ADD CONSTRAINT orden_de_venta_pk PRIMARY KEY ( id_orden );

CREATE TABLE pais (
    id_pais     INTEGER NOT NULL,
    nombre_pais VARCHAR2(50) NOT NULL
);

ALTER TABLE pais ADD CONSTRAINT pais_pk PRIMARY KEY ( id_pais );

CREATE TABLE producto (
    id_producto            INTEGER NOT NULL,
    nombre_producto        VARCHAR2(50) NOT NULL,
    precio                 FLOAT NOT NULL,
    categoria_id_categoria INTEGER NOT NULL
);

ALTER TABLE producto ADD CONSTRAINT producto_pk PRIMARY KEY ( id_producto );

CREATE TABLE vendedor (
    id_vendedor       INTEGER NOT NULL,
    nombre_vendedor   VARCHAR2(50) NOT NULL,
    apellido_vendedor VARCHAR2(50) NOT NULL,
    pais_id_pais      INTEGER NOT NULL
);

ALTER TABLE vendedor ADD CONSTRAINT vendedor_pk PRIMARY KEY ( id_vendedor );

ALTER TABLE cliente
    ADD CONSTRAINT cliente_pais_fk FOREIGN KEY ( pais_id_pais )
        REFERENCES pais ( id_pais );

ALTER TABLE detalle
    ADD CONSTRAINT detalle_orden_de_venta_fk FOREIGN KEY ( orden_de_venta_id_orden )
        REFERENCES orden_de_venta ( id_orden );

ALTER TABLE detalle
    ADD CONSTRAINT detalle_producto_fk FOREIGN KEY ( producto_id_producto )
        REFERENCES producto ( id_producto );

ALTER TABLE detalle
    ADD CONSTRAINT detalle_vendedor_fk FOREIGN KEY ( vendedor_id_vendedor )
        REFERENCES vendedor ( id_vendedor );

ALTER TABLE orden_de_venta
    ADD CONSTRAINT orden_de_venta_cliente_fk FOREIGN KEY ( cliente_id_cliente )
        REFERENCES cliente ( id_cliente );

ALTER TABLE producto
    ADD CONSTRAINT producto_categoria_fk FOREIGN KEY ( categoria_id_categoria )
        REFERENCES categoria ( id_categoria );

ALTER TABLE vendedor
    ADD CONSTRAINT vendedor_pais_fk FOREIGN KEY ( pais_id_pais )
        REFERENCES pais ( id_pais );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
